meta_product_name: "Léo Chaput"
meta_title: "Léo Chaput - Développeur web Fullstack"
meta_description: "Développeur web fullstack pa"
meta_image: "test-responsive.png" # should exist in `app/assets/images/`
